### ISSUE TITLE
minor adjustment

### ISSUE THREAD

**Issue by Vutsuak16** [mr-karan/fritter#1]
There is no point using the 24-hour clock if you are using the sun/moon emoji. Do you want me to add a fix..?

**Comment by mr-karan** [comment]
No. You can fork and customise 😆

**Comment by Vutsuak16** [comment]
😑

**Comment by mr-karan** [comment]
I'm the [BDFL](https://en.wikipedia.org/wiki/Benevolent_dictator_for_life) for this project

**Comment by Vutsuak16** [comment]
And only you use it 😂
